# Generated by Django 4.2.5 on 2023-11-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_storagebox_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagebox',
            name='created_at',
        ),
    ]
