# Generated by Django 4.2.5 on 2023-11-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0004_storagebox_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagebox',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='storagebox',
            name='availability_end_date',
            field=models.DateTimeField(null=True, verbose_name='Date de fin de disponibilité'),
        ),
        migrations.AddField(
            model_name='storagebox',
            name='availability_start_date',
            field=models.DateTimeField(null=True, verbose_name='Date de début de disponibilité'),
        ),
    ]
