# Generated by Django 4.2.5 on 2023-11-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0006_storagebox_availability_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebox',
            name='availability_end_date',
            field=models.DateField(null=True, verbose_name='Date de fin de disponibilité'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='availability_start_date',
            field=models.DateField(null=True, verbose_name='Date de début de disponibilité'),
        ),
    ]
