# Generated by Django 4.2.5 on 2023-11-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0007_alter_storagebox_availability_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storagebox',
            name='availability_constraint',
        ),
        migrations.AddConstraint(
            model_name='storagebox',
            constraint=models.CheckConstraint(check=models.Q(('availability_end_date__gte', models.F('availability_start_date'))), name='availability_constraint'),
        ),
    ]
