# Generated by Django 4.2.5 on 2023-11-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0008_remove_storagebox_availability_constraint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagebox',
            options={},
        ),
    ]
