# Generated by Django 4.2.5 on 2023-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0009_alter_storagebox_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebox',
            name='availability_end_date',
            field=models.DateField(null=True, verbose_name='Availability end date'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='availability_start_date',
            field=models.DateField(null=True, verbose_name='Availability start date'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='storage_type',
            field=models.CharField(choices=[('GARAGE_BOX', 'Garage'), ('CELLAR', 'Cellar'), ('ATTIC', 'Attic'), ('ROOM', 'Room'), ('HANGAR_WAREHOUSE', 'Hangar / Warehouse'), ('PARKING', 'parking spot')], max_length=32, verbose_name='Storage type'),
        ),
    ]
